NAME: '2d_SAM_ac34_slice1.0_aff1.0_cross1.0_interaction1.0_Lsam0.1_L3d1.0_interation1.0_v6'

MODEL:
    input_nc: 1
    output_nc: 16
    filter_channel: 16
    if_sigmoid: False

TRAIN:
    mode: 'x-y-z-2'
    resume: False
    if_valid: True
    if_seg: True
    cache_path: '/h3cstore_ns/hyshi/CAD_SAM2/caches/'
    save_path: '/h3cstore_ns/hyshi/CAD_SAM2/models/'
    pad: 0
    loss_func: 'WeightedMSELoss'   # 'WeightedBCELoss', 'BCELoss'
    affs0_weight: 1
    loss_mode: 'trunc'
    if_verse: False
    only_z: False
    opt_type: 'adam'
    total_iters: 400000
    warmup_iters: 0
    base_lr: 0.0001
    end_lr: 0.0001
    display_freq: 100
    valid_freq: 1000
    save_freq: 1000
    decay_iters: 100000
    weight_decay: ~
    power: 1.5
    if_2d_SAM_CPS: False
    batch_size: 16
    num_workers: 4
    if_cuda: True
    if_2d_3d: True
    loss_weight_2d_3d: 1.0
    loss_weight_2d_SAM: 0.1  # lamda 3
    interaction: True
    loss_interaction: 1.0  # lamda 2
    loss_interaction_2d: 1.0  # lamda 4
    loss_2d_slice_weight: 1.0
    loss_cross_weight: 1.0  # lamda 1
    loss_aff1: 1.0
    ct_weight: 0.1
    random_seed: 555  # -1 is none

DATA:
    if_sparse: False
    sparse_id: 0
    dataset_name: 'ac4'  # 'snemi3d-ac3', 'cremi-A', 'cremi'
    valid_dataset: 'ac3'  # 'snemi3d-ac3', 'cremi-A', 'cremi'
    train_split: 80
    test_split: 100
    data_folder: '/h3cstore_ns/Backbones/data'
    patch_size:
        - 256
        - 256
    shift_channels: ~
    padding: 50
    if_dilate: True
    widen_way: True
    if_bg: True
    if_scale_aug: True
    if_filp_aug: True
    if_rotation_aug: True
    if_intensity_aug: True
    if_elastic_aug: True


TEST:
    pad: 0
    model_name: '2021-05-09--14-40-12_seg_general_ac4_data80_c16_norm_wz2_aug3'